[project]
name = "example-agent"
version = "0.1.0"
description = "Example Agent using Pydantic AI and LangGraph"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=3.4.3",
    "devtools>=0.12.2",
    "langgraph>=0.2.74",
    "pydantic-ai>=0.0.24",
]
